package com.pricing.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.pricing.model.enums.Category;

import lombok.Getter;
import lombok.Setter;

/**
 * Class that maps the product table
 * 
 * @author beatr
 *
 */
@Getter
@Setter
@Entity
@Table(name="product")
public class Product {

	/**
	 * Id generated by the sequence
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false)
    @SequenceGenerator(name = "productSeq", sequenceName = "product_sequence", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "productSeq")
	private Long id;
	
	/**
	 * Product name
	 */
	@Column(name="name", nullable=false)
	private String name;
	
	/**
	 * Product's category
	 */
	@Column(name="category", nullable=false)
	@Enumerated(EnumType.ORDINAL)
	private Category category;
}
