package com.pricing.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

/**
 * Supplier class, map supplier database table
 * 
 * @author beatr
 *
 */
@Getter
@Setter
@Entity
@Table(name="supplier")
public class Supplier 
{
	/**
	 * Id generated by the sequence
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false)
    @SequenceGenerator(name = "supplierSeq", sequenceName = "supplier_sequence", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "supplierSeq")
	private Long id;
	
	/**
	 * Supplier name
	 */
	@Column(name="name", nullable = false)
	private String name;
	
	/**
	 * Supplier email
	 */
	@Column(name="email", unique = true, nullable = false)
	private String email;
}
